# Generated by Django 4.2.4 on 2023-09-09 13:05

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('gender', models.CharField(choices=[('other', 'Other'), ('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('number', models.CharField(blank=True, max_length=12, null=True)),
                ('cin', models.CharField(blank=True, max_length=12, null=True)),
                ('birthdate', models.DateField(blank=True, default=datetime.date(2001, 1, 1), null=True)),
                ('otp', models.CharField(blank=True, max_length=10)),
                ('picture', models.ImageField(blank=True, default='user.png', upload_to='profileImage/%Y/%m/%d/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=255, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('gender', models.CharField(choices=[('other', 'Other'), ('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('number', models.CharField(blank=True, max_length=12, null=True)),
                ('cin', models.CharField(blank=True, max_length=8)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('picture', models.ImageField(blank=True, default='store.png', upload_to='storeImg/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('startDate', models.DateField(default=django.utils.timezone.now)),
                ('numberOfSub', models.PositiveIntegerField()),
                ('typeOfNumberSub', models.CharField(choices=[('year', 'Year'), ('month', 'Month'), ('day', 'Day')], max_length=10)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_sub', to='account.activity')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_sub', to='account.member')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_profile', to='account.person'),
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hireDate', models.DateField(blank=True, null=True)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coach_profile', to='account.person')),
            ],
        ),
    ]
