# Generated by Django 4.2.4 on 2023-09-09 22:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='activity',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='coach_activity', to='account.activity'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
