# Generated by Django 4.2.4 on 2023-09-10 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_coach_activity_alter_subscription_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_sub', to='account.activity'),
        ),
    ]
