# Generated by Django 4.2.4 on 2023-09-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_coach_hiredate'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='TimeEmail',
            field=models.DateField(blank=True, null=True),
        ),
    ]
