# Generated by Django 4.2.4 on 2023-10-10 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_person_is_active_person_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
    ]
