# Generated by Django 4.2.4 on 2023-10-16 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_sub', to='account.member'),
        ),
    ]
