# Generated by Django 4.2.4 on 2023-10-16 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_subscription_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='address',
            field=models.CharField(default=2, max_length=300),
            preserve_default=False,
        ),
    ]
