# Generated by Django 4.2.4 on 2023-10-20 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_subscription_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='is_active',
        ),
    ]
