# Generated by Django 4.2.4 on 2023-10-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_person_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='gym',
            name='linkFacebook',
            field=models.URLField(default='#', null=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='linkInstagram',
            field=models.URLField(default='#', null=True),
        ),
    ]
