# Generated by Django 4.2.4 on 2023-10-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='linkFacebook',
            field=models.URLField(blank=True, default='#', null=True),
        ),
        migrations.AlterField(
            model_name='gym',
            name='linkInstagram',
            field=models.URLField(blank=True, default='#', null=True),
        ),
    ]
