# Generated by Django 4.2.4 on 2023-11-06 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_gym_linkfacebook_alter_gym_linkinstagram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=255),
        ),
    ]
