# Generated by Django 4.2.4 on 2023-11-08 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_person_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='member',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='member_sub', to='account.member'),
            preserve_default=False,
        ),
    ]
