# Generated by Django 4.2.4 on 2023-11-08 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_subscription_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
