# Generated by Django 4.2.4 on 2023-11-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_activity_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
