# Generated by Django 4.2.4 on 2023-11-12 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_activity_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='activity',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='activity_sub', to='account.activity'),
            preserve_default=False,
        ),
    ]
